### ISSUE TITLE
the version of librosa needs to >=0.8.1 and <0.9.0

### ISSUE THREAD

**Issue by ChekeLee** [haoheliu/voicefixer#16]
In setup.py, librosa needs to be >=0.8.1 and <0.9.0
When I first install librosa==0.9.0, an error occurs as the following:
```
Traceback (most recent call last):
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/streamlit/script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "/Users/li/PycharmProjects/voicefixer/test/streamlit.py", line 18, in <module>
    voice_fixer = init_voicefixer()
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/streamlit/caching/cache_utils.py", line 145, in wrapper
    return get_or_create_cached_value()
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/streamlit/caching/cache_utils.py", line 137, in get_or_create_cached_value
    return_value = func(*args, **kwargs)
  File "/Users/li/PycharmProjects/voicefixer/test/streamlit.py", line 14, in init_voicefixer
    return VoiceFixer()
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/voicefixer/base.py", line 12, in __init__
    self._model = voicefixer_fe(channels=2, sample_rate=44100)
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/voicefixer/restorer/model.py", line 158, in __init__
    freeze_parameters=freeze_parameters,
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/voicefixer/tools/modules/fDomainHelper.py", line 24, in __init__
    pad_mode=pad_mode, freeze_parameters=freeze_parameters)
  File "/Users/li/opt/anaconda3/envs/voicefixer/lib/python3.7/site-packages/torchlibrosa/stft.py", line 177, in __init__
    fft_window = librosa.util.pad_center(fft_window, n_fft)
TypeError: pad_center() takes 1 positional argument but 2 were given
```
The reason is librosa==0.9.0 modified librosa.util.pad_center
librosa==0.9.0 pad_center document:https://librosa.org/doc/0.9.0/generated/librosa.util.pad_center.html?highlight=pad_center#librosa.util.pad_center
librosa==0.8.0 pad_center document:https://librosa.org/doc/0.8.1/generated/librosa.util.pad_center.html?highlight=pad_center#librosa.util.pad_center

**Comment by haoheliu** [comment]
Thanks for reporting the issue. I'll make an update later.
