### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by zhangzhangthink** [haoheliu/voicefixer#18]
Hello, as a novice in speech processing, I want to ask you a question, that is, I am running  test.py  the specific errors are as follows. I hope all teachers can teach me some solutions to this problem. Thank you very much!
![G{3KE9HK`K65KGEGEZTS8LR](https://user-images.githubusercontent.com/90177652/160267531-d825e69f-3a65-4902-bb01-2a2266b3004f.png)

**Comment by haoheliu** [comment]
Sorry for the late reply. It's hard to tell the reason with the information you provided. I haven't tested VoiceFixer on Windows so that might be a potential issue. 

I would recommend using the google collab to reproduce VoiceFixer and if you encounter a problem you can share the notebook with me. Thanks!

**Comment by snufas** [comment]
@haoheliu 
- same issue on Linux, wsl2 that is.
- Can you investigate please?
- Could python version play any role in this? 
- Would love to try this out...

Thanks for your work.

**Comment by haoheliu** [comment]
@snufas Apologize for the inconvinence. I tried but cannot reproduce this issue on my computer. Could you provide more context if you like? 
I guess the main issue is from the windows system. I quick solution is trying this repo on Google Colab.

**Comment by snufas** [comment]
@haoheliu 
"failed finding central directory"
I am sure notebook will work, but i would like to run that locally.
Is there a manual fix for "central directory"?
Thanks for quick responce.

**Comment by snufas** [comment]
@haoheliu 
the error output below:

(voicefixer) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/voicefixer# python test/test.py
Initializing VoiceFixer...
Traceback (most recent call last):
  File "/home/snufas/github_projects/voicefixer/test/test.py", line 41, in <module>
    voicefixer = VoiceFixer()
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/voicefixer-0.0.18-py3.9.egg/voicefixer/base.py", line 16, in __init__
    torch.load(
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
(voicefixer) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/voicefixer#


I have to say it is definitely issue with the code somewhere... 
WSL2 is Linux  not windows, and as i see many other people has saime issue. 
please investigate this properly , install wsl2 if you can very easy, it would help many people if you find the issue, rather then saying it is our issue...
Thanks.

**Comment by utahboy3502** [comment]
> @haoheliu the error output below:
> 
> (voicefixer) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/voicefixer# python test/test.py Initializing VoiceFixer... Traceback (most recent call last): File "/home/snufas/github_projects/voicefixer/test/test.py", line 41, in voicefixer = VoiceFixer() File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/voicefixer-0.0.18-py3.9.egg/voicefixer/base.py", line 16, in **init** torch.load( File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 705, in load with _open_zipfile_reader(opened_file) as opened_zipfile: File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 242, in **init** super(_open_zipfile_reader, self).**init**(torch._C.PyTorchFileReader(name_or_buffer)) RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory (voicefixer) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/voicefixer#
> 
> I have to say it is definitely issue with the code somewhere... WSL2 is Linux not windows, and as i see many other people has saime issue. please investigate this properly , install wsl2 if you can very easy, it would help many people if you find the issue, rather then saying it is our issue... Thanks.

I have found the solution for this error.
its because of failure of downloading the pretrained checkpoint.
I manually downloaded the pretrained model of voicefixer: 
model.ckpt-14900000_trimmed.pt
vf.ckpt

I downloaded the two pretrained model via https://zenodo.org/record/5600188#.YxGlfexBxHQ
and replaced to ~/cache/~

and it worked out!

**Comment by snufas** [comment]
@utahboy3502 
I created a "cach" folder in the main directory and still does not work, same error
where does cach folder needs to be???

**Comment by utahboy3502** [comment]
> @utahboy3502 I created a "cach" folder in the main directory and still does not work, same error where does cach folder needs to be???

Download the pretrained model from the link above,
and replaced it with the original like the following:

<img width="810" alt="CleanShot 2022-09-03 at 16 07 50@2x" src="https://user-images.githubusercontent.com/82129086/188260090-dd4f303e-9a23-420d-a635-254ca8625069.png">

**Comment by snufas** [comment]
@utahboy3502 
Thank you for your help, however I still run into  same issue.

I have made 2 directories as you suggested:

snufas/.cach/voicefixer/analysis_module/checkpoints/vf.ckpt"
snufas/.cach/voicefixer/synthesis_module/44100/model.ckpt-1490000_trimed.pt"

I am running this on the conda environment, I'm not sure if that creates an issue or not

however the error below

(voicefixer) root@DESKTOP-7A6UGRU:/home/snufas/github_projects/voicefixer# voicefixer --infile test/utterance/original/original.flac --outfile test/utterance/original/original_processed.flac
Initializing VoiceFixer
Traceback (most recent call last):
  File "/root/miniconda3/envs/voicefixer/bin/voicefixer", line 106, in <module>
    voicefixer = VoiceFixer()
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/voicefixer/base.py", line 24, in __init__
    torch.load(
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/root/miniconda3/envs/voicefixer/lib/python3.9/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by utahboy3502** [comment]
Here is the screenshot of showing pretrained model at the following directory.
![Screenshot from 2022-09-05 13-17-34](https://user-images.githubusercontent.com/82129086/188360211-a545e405-7195-48d5-8122-da3c17a0b77e.png)

watch out if the size of pretrained model matches with your version!

![Screenshot from 2022-09-05 13-19-44](https://user-images.githubusercontent.com/82129086/188360228-32e814dc-d149-440e-b6fa-2cb821f1c554.png)

One thing to note that I did not have to manually create directory.
There was already directory created at the path.
I was simply downloading the pretrained the model and replaced it.


I am also running it in conda environment (Anaconda, not midniconda).

Here are the steps what I would do 

 1. completely remove conda environment 
 2. remove voicefixer directory.
 3. restart the system
 4. create new conda env
 5. pip3 install voicefixer
 6. git clone voicefixer
 7. download the pretrined the model from the link above
 8. replace it with cache directory and check the size if it is correct version.
 9. and run test/test.py
 
I was facing the same issue as you had but it worked out!
![Screenshot from 2022-09-05 13-29-43](https://user-images.githubusercontent.com/82129086/188360750-4c764ff1-4ce4-40a0-bd63-ac31f0930f2e.png)

**Comment by Kunjesh07** [comment]
I deleted .cache folder when I got the error and try to rerun streamlit command i successfully got the output (Windows)
