### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by Sinicyn78** [haoheliu/voicefixer#59]
(Voicefixer) C:\Temp\voicefixer>voicefixer --help
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Temp\voicefixer\voicefixer\__init__.py", line 13, in <module>
    from voicefixer.vocoder.base import Vocoder
  File "C:\Temp\voicefixer\voicefixer\vocoder\base.py", line 2, in <module>
    from voicefixer.tools.wav import read_wave, save_wave
  File "C:\Temp\voicefixer\voicefixer\tools\wav.py", line 6, in <module>
    import librosa
  File "C:\Temp\voicefixer\venv\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Temp\voicefixer\venv\Lib\site-packages\librosa\core\__init__.py", line 9, in <module>
    from .constantq import *  # pylint: disable=wildcard-import
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Temp\voicefixer\venv\Lib\site-packages\librosa\core\constantq.py", line 1059, in <module>
    dtype=np.complex,
          ^^^^^^^^^^
  File "C:\Temp\voicefixer\venv\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'complex_'?

**Comment by andrew-r-marchand** [comment]
Following the installation directions (modified for conda env), I get this same error, running on Python 3.9.

            1. conda create --name python-voicefixer  python=3.9
            2. conda activate python-voicefixer
            3. pip install voicefixer==0.1.2
            4. conda install git
            5. git clone https://github.com/haoheliu/voicefixer.git
            6. cd voicefixer
            7. python test/test.py # test script

Results in same as Sinicyn78. Had this working many months back on a different system and LOVED it, so hoping to figure out a fix.
