### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by suhitaghosh10** [haoheliu/voicefixer#64]
I am getting this issue, after runing _**python3 test/test.py**_
My pytorch version is 2.0.0+cu117

Initializing VoiceFixer...
Traceback (most recent call last):
  File "/home/sughosh/voicefixer/test/test.py", line 41, in <module>
    voicefixer = VoiceFixer()
                 ^^^^^^^^^^^^
  File "/home/sughosh/miniconda3/envs/emo/lib/python3.11/site-packages/voicefixer/base.py", line 13, in __init__
    self._model = voicefixer_fe(channels=2, sample_rate=44100)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sughosh/miniconda3/envs/emo/lib/python3.11/site-packages/voicefixer/restorer/model.py", line 180, in __init__
    self.vocoder = Vocoder(sample_rate=44100)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sughosh/miniconda3/envs/emo/lib/python3.11/site-packages/voicefixer/vocoder/base.py", line 19, in __init__
    self._load_pretrain(Config.ckpt)
  File "/home/sughosh/miniconda3/envs/emo/lib/python3.11/site-packages/voicefixer/vocoder/base.py", line 25, in _load_pretrain
    self.model = Generator(Config.cin_channels)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sughosh/miniconda3/envs/emo/lib/python3.11/site-packages/voicefixer/vocoder/model/generator.py", line 34, in __init__
    nn.utils.parametrizations.weight_norm(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.nn.utils.parametrizations' has no attribute 'weight_norm'

**Comment by itswalli** [comment]
Exactly the same for me

**Comment by SoshyHayami** [comment]
Go to the Generator's code and remove the "parametrizations" from the code. in other words, change all the nn.utils.parametrizations.weight_norm to nn.utils.weight_norm
