### ISSUE TITLE
Colab bug - Unable to run

### ISSUE THREAD

**Issue by juanalonso** [haoheliu/voicefixer#65]
Usin Google Colab, the test script cell

```
! pip install voicefixer==0.0.17 &> /dev/null
! git clone https://github.com/haoheliu/voicefixer.git
%cd voicefixer
! python3 test/test.py
%cd ..
```
returns this error

```
Initializing VoiceFixer...
/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/content/voicefixer/test/test.py", line 41, in <module>
    voicefixer = VoiceFixer()
  File "/usr/local/lib/python3.10/dist-packages/voicefixer/base.py", line 12, in __init__
    self._model = voicefixer_fe(channels=2, sample_rate=44100)
  File "/usr/local/lib/python3.10/dist-packages/voicefixer/restorer/model.py", line 152, in __init__
    self.f_helper = FDomainHelper(
  File "/usr/local/lib/python3.10/dist-packages/voicefixer/tools/modules/fDomainHelper.py", line 22, in __init__
    self.stft = STFT(n_fft=window_size, hop_length=hop_size,
  File "/usr/local/lib/python3.10/dist-packages/torchlibrosa/stft.py", line 177, in __init__
    fft_window = librosa.util.pad_center(fft_window, n_fft)
TypeError: pad_center() takes 1 positional argument but 2 were given
```
Thanks!

**Comment by haoheliu** [comment]
This looks like a dependency issue. Will look into this later

**Comment by king-ali** [comment]
Running below in Part 1
```
!pip install torch==1.13.0
!pip install librosa==0.9.2
```

and below in Part 2 solved my errors
```
!pip install --upgrade protobuf==3.20.0
!pip install Keras-Preprocessing
!pip install keras==2.6
!pip install tensorflow==2.15

```
